<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0-windows</TargetFramework>
        <Nullable>enable</Nullable>
        <UseWPF>true</UseWPF>
        <ImplicitUsings>enable</ImplicitUsings>
        <RootNamespace>UselessTool.Theme</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <Page Update="Resources\Light\White.xaml">
        <Generator>MSBuild:Compile</Generator>
        <XamlRuntime>Wpf</XamlRuntime>
        <SubType>Designer</SubType>
      </Page>
      <Page Update="Resources\Dark\Black.xaml">
        <Generator>MSBuild:Compile</Generator>
        <XamlRuntime>Wpf</XamlRuntime>
        <SubType>Designer</SubType>
      </Page>
      <Page Update="Resources\Themes\Dark\Black.xaml">
        <Generator>MSBuild:Compile</Generator>
      </Page>
      <Page Update="Resources\Themes\Light\White.xaml">
        <Generator>MSBuild:Compile</Generator>
      </Page>
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Resources\Styles\" />
      <Folder Include="Resources\Icons\" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\UselessTool.Bases\UselessTool.Bases.csproj" />
    </ItemGroup>

</Project>
